server:
  servlet:
    context-path: /api/v1
  port: 8085

spring:
  application:
    name: spring-boot-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true